version: '3.1'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplerest
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    # volumes:
    #   - ./dbdata:/var/lib/mysql/